stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_IMAGE: "$DOCKER_USERNAME/event-backend"

default:
  tags:
    - docker

# ---------------- BUILD (Restore + Build ერთ job-ში) ----------------
build_backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages/
      - obj/
      - bin/
  script:
    # Restore + Build ერთად
    - dotnet restore EventManagementAPI.csproj
    - dotnet build EventManagementAPI.csproj -c Release
  rules:
    - if: '$CI_COMMIT_BRANCH'


# ---------------- DOCKER ----------------
docker_backend:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  script:
  - |
    if [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then
      TAG="${CI_COMMIT_SHORT_SHA}-staging"
    elif [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
      TAG="${CI_COMMIT_SHORT_SHA}-production"
    else
      echo "No env tag for this branch"
      exit 0
    fi

    echo "Using tag: $TAG"
    docker build -t $DOCKER_IMAGE:$TAG .
    docker push $DOCKER_IMAGE:$TAG
    
  rules:
  - if: '$CI_COMMIT_BRANCH'

    

# ---------------- PRODUCTION ----------------
deploy_production:
  stage: deploy
  image: alpine
  environment:
    name: production
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

  script:
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker network inspect app-network >/dev/null 2>&1 || docker network create app-network"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker pull $DOCKER_IMAGE:latest"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker stop backend-prod || true"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker rm backend-prod || true"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker run -d --name backend-prod
     --network app-network -e ASPNETCORE_ENVIRONMENT=Production -p 5282:3000 $DOCKER_IMAGE:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH'




