stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_IMAGE: "$DOCKER_USERNAME/event-backend"

default:
  tags:
    - docker

# ---------------- BUILD (Restore + Build ერთ job-ში) ----------------
build_backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages/
      - obj/
      - bin/
  script:
    # Restore + Build ერთად
    - dotnet restore EventManagementAPI.csproj
    - dotnet build EventManagementAPI.csproj -c Release
  rules:
    - if: '$CI_COMMIT_BRANCH'


# ---------------- DOCKER ----------------
docker_backend:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    # Docker image შექმნა და push-ი DockerHub-ზე
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH'

    

# ---------------- PRODUCTION ----------------
deploy_production:
  stage: deploy
  image: alpine
  environment:
    name: production
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

  script:
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker pull $DOCKER_IMAGE:latest"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker stop backend-prod || true"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker rm backend-prod || true"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker run -d --name backend-prod --network app-network -e ASPNETCORE_ENVIRONMENT=Production -p 5000:8080 $DOCKER_IMAGE:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'




